# Push these as binder/requirements.txt`,
# and get the latest transitive ones from the running binder,
# by issuing in its terminal:
#
#     conda list
#     pip freeze
#
# ... and subtract the 2 install-sets.
name: gearshift
channels:
  - conda-forge
  - defaults
dependencies:
  - boltons
  - coveralls
  - docopt
  - docutils
  - graphviz
  - ipympl
  - jsonschema
  - jupyter
  - jupytext
  - matplotlib
  - nb_black
  - numpy
  - octave
  - openpyxl
  - pandas
  - papermill
  - pip
  - pyarrow
  - ruamel.yaml
  - scipy
  - sphinx
  - toolz
  - wheel
  - pip:
    - schedula>=1.1.1
    - PyYAML
    - click
    - pandas
    - click_log
    - tqdm
    - regex
    - XlsxWriter
    - openpyxl
    - xlrd